- name: Install Arc Theme
  apt:
    name: arc-theme
    state: present

- name: Configure GTK Theme
  become_user: '{{ user }}'
  dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
  loop:
   - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Arc-Darker'" }
   - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'DMZ-Black'" }
   - { key: "/org/gnome/desktop/interface/clock-show-date", value: "true" }
   - { key: "/org/gnome/nautilus/desktop/volumes-visible", value: "false" }
   - { key: "/org/gnome/shell/enabled-extensions", value: "['user-theme@gnome-shell-extensions.gcampax.github.com']" }
   - { key: "/org/gnome/shell/extensions/user-theme/name", value: "'Arc-Dark'" }
   - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "36" }
