- name: Install OpenJDK
  apt:
    pkg: openjdk-8-jdk
    state: present

# TODO: Obter o caminho do JDK automaticamente após a instalação e setar uma variável
- name: Set $JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
