- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repo
  apt_repository:
    # Até o momento, o docker-ce só está disponível para Ubuntu bionic no canal edge
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge'
    filename: 'docker-ce'
    state: present

- name: Install Docker
  apt:
    pkg: docker-ce
    state: present
